import type { Groth16Proof } from "snarkjs";
import type { ConsumerNodeContext, KnownNode } from "../types";
import {
	mapGrpcResponseToGroth16Proof,
	sendProofRequest,
	verifyProof,
	verifyPublicSignals,
	type ProofInput,
} from "./proof-requestor";
import { getErrorMessage } from "../utils";

export type Task<Input, Output> = (input: Input) => Promise<Output>;

export type ProofTaskResult = {
	proof: Groth16Proof;
	publicSignals: string[];
	outputFile: string;
};

export function createProofTask(
	input: ProofInput,
	outputFile: string,
	verificationKey: string,
	timeoutMs = 30000,
): Task<KnownNode, ProofTaskResult> {
	return async (node: KnownNode) => {
		const response = await sendProofRequest(node, input, timeoutMs);
		const parsedProof = mapGrpcResponseToGroth16Proof(response);
		if (
			!verifyPublicSignals(
				response.getPublicSignalsList(),
				input.startingBalance,
				input.transactions,
			)
		)
			throw new Error(
				`Public signals do not match input generated by node ${node.nodeId}`,
			);
		const isValid = await verifyProof(
			parsedProof,
			response.getPublicSignalsList(),
			verificationKey,
		);
		if (!isValid) {
			throw new Error(`Proof generated by node ${node.nodeId} is invalid!`);
		}
		return {
			proof: parsedProof,
			publicSignals: response.getPublicSignalsList(),
			outputFile,
		};
	};
}

/**
 * Wait for one event loop cycle to ensure that all async tasks are executed.
 */
function waitOneEventLoopCycle() {
	return new Promise((resolve) => setTimeout(resolve, 0));
}

type Metric = {
	nodeId: string;
	timestamp: number;
	operation: "START" | "SUCCESS" | "FAIL";
};

/**
 * If filepath is provided, setup metrics file and return a function to
 * append to it and a function to close the file.
 * If no filepath is provided, return a function to append to the console
 * and an empty cleanup function.
 */
function setupMetrics(filePath?: string) {
	if (filePath) {
		const file = Bun.file(filePath);
		const writer = file.writer();
		return {
			append: (metric: Metric) => {
				writer.write(JSON.stringify(metric));
				writer.write("\n");
			},
			cleanup: () => writer.end(),
		};
	}
	return {
		append: (metric: Metric) => console.log(JSON.stringify(metric)),
		// no-op
		cleanup: () => {},
	};
}
export async function executeTasks<T>(
	tasks: ((node: KnownNode) => Promise<T>)[],
	nodeContext: ConsumerNodeContext,
	options: {
		metricsFile?: string;
	} = {},
): Promise<T[]> {
	const results: T[] = [];
	const expectedResults = tasks.length;
	const idleNodes = [...nodeContext.getCurrentNodeState().values()];
	const { append: appendMetrics, cleanup: cleanupMetrics } = setupMetrics(
		options.metricsFile,
	);
	while (results.length < expectedResults) {
		const idleNode = idleNodes.pop();
		if (!idleNode) {
			// no idle nodes available
			// wait for a bit and try again
			await waitOneEventLoopCycle();
			continue;
		}
		const task = tasks.shift();
		if (!task) {
			idleNodes.push(idleNode);
			// no tasks left
			// wait for a bit (a task may fail and be requeued)
			await waitOneEventLoopCycle();
			continue;
		}
		const executeTask = async () => {
			try {
				console.log(`Node ${idleNode.nodeId} executing task`);
				appendMetrics({
					nodeId: idleNode.nodeId,
					timestamp: Date.now(),
					operation: "START",
				});
				const result = await task(idleNode);
				appendMetrics({
					nodeId: idleNode.nodeId,
					timestamp: Date.now(),
					operation: "SUCCESS",
				});
				results.push(result);
				idleNodes.push(idleNode);
				console.log(
					`Node ${idleNode.nodeId} completed task, returning to idle queue. Tasks remaining: ${tasks.length}.`,
				);
			} catch (error) {
				console.error(
					`Error processing task by node ${idleNode.nodeId}: ${getErrorMessage(error)}`,
				);
				appendMetrics({
					nodeId: idleNode.nodeId,
					timestamp: Date.now(),
					operation: "FAIL",
				});
				// requeue the task
				tasks.push(task);
				// don't add the node to the idle queue, assume it's broken
				console.log(
					`Node ${idleNode.nodeId} failed to complete task, not returning to idle queue. Tasks remaining: ${tasks.length}.`,
				);
			}
		};
		executeTask();
	}
	cleanupMetrics();
	return results;
}
